### ISSUE TITLE
中文解析会报错

### ISSUE THREAD

**Issue by httphttp** [xialeistudio/wxbizmsgcrypt-nodejs#2]
```
wxbizmsgcrypt.encryptMsg('你好', timestamp, nonce)
...
wxbizmsgcrypt.decryptMsg(t.xml.MsgSignature, timestamp, nonce, s).then((xml) => {
  console.log(xml)
  // console.log(Base64.decode(xml))
}).catch(e => console.log(e.stack))

//--------------------
Error: appId is invalid
    at Prpcrypt.decrypt (/Users/lwb/WebstormProjects/test/tanghushi/src/Prpcrypt.js:84:13)
    at WxBizMsgCrypt._callee$ (/Users/lwb/WebstormProjects/test/tanghushi/src/WxBizMsgCrypt.js:61:15)
```

**Comment by xialeistudio** [comment]
不是中文解析报错，这个只能处理微信的xml
